# Generated by Django 5.1.4 on 2025-02-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(editable=False, max_length=14, unique=True),
        ),
    ]
