# Generated by Django 5.1.4 on 2025-03-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_experience_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
