# Generated by Django 5.1.4 on 2025-03-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contacts_facebook_contacts_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='link',
            new_name='reference',
        ),
    ]
